#paypal:
#  client-id: AftdefUpAl-QODhNnETlhmekGc122NG1-fp9EoNuvAd4S9ClcuBA12CtykYV74kZR1DscwDZgT19pVio
#  client-secret: EDfCd-nNB_SMyedHBhjw9KBhiWkWpMudOwgStUIrEEaVmwmvQ0J8ukmvxNGLx1OQ_kbCdpKg1GlBzd8K
#  mode: sandbox # We use sandbox for testing and 'live' for Production

vipps:
  mode: sandbox  # or production
  client:
    id: your_vipps_client_id
    secret: your_vipps_client_secret
  subscription:
    key: your_vipps_subscription_key
  merchant:
    serial: your_vipps_merchant_serial_number
  api:
    url: https://api.vipps.no
  success_url: http://your-success-url
  cancel_url: http://your-cancel-url


##  success-url: https://paypal-integration-8f06aefa18a5.herokuapp.com/payment/success
##  cancel-url: https://paypal-integration-8f06aefa18a5.herokuapp.com/payment/cancel
#  success-url: http://localhost:8080/payment/success
#  cancel-url: http://localhost:8080/payment/cancel



#logging:
#  level:
#    root: DEBUG
spring:
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/templates/


